import { useEffect } from "react";
import privacypolicy from "../../assets/background/jhj.jpg";
import bgImage from "../../assets/background/home background.avif";

function Termcondition() {
  useEffect(() => {
    window.scrollTo(0, 0), (document.title = "Term Condition : Doctor's Diary");
  }, []);

  return (
    <div
      className="mx-auto max-w-full px-4 sm:px-6 lg:px-8 py-8 rounded-lg shadow-lg"
      style={{
        backgroundImage: `url(${bgImage})`,
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        backgroundPosition: "center",
      }}
    >
      <div className="bg-primary text-white rounded-lg shadow-lg p-8 md:p-16">
        <h1 className="text-4xl font-extrabold mb-6 text-white text-center">
          Terms &amp; Conditions
        </h1>
        <p className="max-w-3xl mx-auto text-base text-center md:text-lg mb-6">
          By using our services, you agree to abide by our Terms & Conditions.
          These guidelines ensure a smooth experience for all users and outline
          the rules governing your use of our platform. Please read through them
          carefully to understand your rights and responsibilities.
        </p>
        <div className="flex justify-center space-x-4">
          <button className="bg-white text-blue-600 font-semibold px-4 py-2 md:px-6 md:py-2 rounded-lg hover:bg-blue-100 transition duration-300 shadow-lg">
            <a href="#cancle"> Read Now ↘️ </a>
          </button>
        </div>
      </div>

      <article className="bg-white/60 backdrop-blur-md backdrop-filter mt-10 p-6 rounded-lg shadow-md text-justify space-y-6">
        <p className="text-sm text-gray-600 mb-4">
          Last updated on Oct 20th, 2024
        </p>
        <p className="text-gray-700">
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules thereunder as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <p className="text-gray-700">
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy
          policy, and Terms of Use for access or usage of domain name
          www.adoctorsdiary.com ('Website'), including the related mobile site
          and mobile application (hereinafter referred to as 'Platform').
        </p>
        <p className="text-gray-700">
          The Platform is owned by Doctors Diary, a company incorporated under
          the Companies Act, 1956 with its registered office at Malti Devi
          Smriti Bhavan Khanpur Akbar Jaunpur Uttar Pradesh, Jaunpur, India
          (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
        </p>
        <p className="text-gray-700">
          Your use of the Platform and services and tools are governed by the
          following terms and conditions ('Terms of Use') as applicable to the
          Platform including the applicable policies which are incorporated
          herein by way of reference. If you transact on the Platform, you shall
          be subject to the policies that are applicable to the Platform for
          such transactions.
        </p>
        <p className="text-gray-700">
          ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR
          AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO
          PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        </p>
        <h5 className="text-lg font-semibold text-blue-600">
          The use of Platform and/or availing of our Services is subject to the
          following Terms of Use:
        </h5>
        <ul className="list-disc list-inside space-y-3 text-gray-700">
          <li>
            To access and use the Services, you agree to provide true, accurate,
            and complete information during and after registration, and you
            shall be responsible for all acts done through the use of your
            registered account on the Platform.
          </li>
          <li>
            Neither we nor any third parties provide any warranty or guarantee
            as to the accuracy, timeliness, performance, completeness, or
            suitability of the information and materials offered on this website
            or through the Services.
          </li>
          <li>
            Your use of our Services and the Platform is solely at your own risk
            and discretion for which we shall not be liable to you in any
            manner.
          </li>
          <li>
            The contents of the Platform and the Services are proprietary to us
            and are licensed to us. You will not have any authority to claim any
            intellectual property rights, title, or interest in its contents.
          </li>
          <li>
            You acknowledge that unauthorized use of the Platform and/or the
            Services may lead to action against you as per these Terms of Use
            and/or applicable laws.
          </li>
          <li>
            You agree to pay us the charges associated with availing the
            Services.
          </li>
          <li>
            You agree not to use the Platform and/or Services for any unlawful
            purposes.
          </li>
          <li>
            You agree and acknowledge that the website and the Services may
            contain links to other third-party websites. On accessing these
            links, you will be governed by their terms of use and policies.
          </li>
          <li>
            You understand that upon initiating a transaction, you are entering
            into a legally binding contract with the Platform Owner for the
            Services.
          </li>
          <li>
            You shall indemnify and hold harmless the Platform Owner, its
            affiliates, and their respective officers and employees from any
            claims arising out of your breach of these Terms.
          </li>
          <li>
            Notwithstanding anything contained in these Terms, the parties shall
            not be liable for any failure to perform an obligation due to a
            force majeure event.
          </li>
          <li>
            These Terms and any related disputes shall be governed by the laws
            of India.
          </li>
          <li>
            All disputes arising out of these Terms shall be subject to the
            exclusive jurisdiction of the courts in Jaunpur, Uttar Pradesh.
          </li>
          <li>
            For any concerns, please contact us using the information provided
            on our website.
          </li>
        </ul>
      </article>
    </div>
  );
}

export default Termcondition;
